### ISSUE TITLE
Problem with linking using docker image

### ISSUE THREAD

**Issue by m2kz** [Ogeon/rust-on-raspberry-pi#17] opened 2016-05-17 06:36 UTC
I've got problem when I'm trying to compile simple project that includes ZeroMQ library.
Firstly, I built docker image with: `sudo docker build --build-arg RUST_GIT_REF=1.8.0 --build-arg PI_TOOLS_GIT_REF=master --tag "rust-cross" .` (without sudo I had problem with docker deamon)
And then I tried to compile with: `sudo docker run --volume /home/mkarczewski/programming/rust/zmqprj/:/home/cross/project --volume /home/mkarczewski/programming/rust/zmqlib/:/home/cross/deb-deps "rust-cross" build --release`
The result I received was  `error: linking with```gcc-sysroot```failed: exit code: 1`, and right now didn't find any solution.

Sample Hello World project compiled without any problem or warning.

**Comment by Ogeon** [comment] 2016-05-17 08:58
Did it say anything more? Anything about missing symbols or libraries?

**Comment by Ragnaroek** [comment] 2016-10-02 06:10
I like to close this one since it is no reproducible and the author lost interest in it?

**Closed as completed** 2016-10-02 10:11 UTC
